### ISSUE TITLE
Need to add links to all tools

### ISSUE THREAD

**Issue by jaybosamiya** [InfoSecIITR/tools#2]
We need to do the following:
- [x] Add links to be able to download all tools
- [ ] Add links to cheatsheets/quickref for each tool, connected to our [reading-material](https://github.com/InfoSecIITR/reading-material) repo maybe?

Note: 2nd point needs further discussion

**Comment by paraschetal** [comment]
Should we add installation scripts too or just the links to the tools?

**Comment by CodeMaxx** [comment]
Hey don't you think this repo is redundant. I'm sure you know about [ctftools](https://github.com/zardus/ctf-tools)

**Comment by paraschetal** [comment]
There are way too many tools in zardus/ctftools and we haven't used most of them. We'll be only adding those tools to our repo which InfoSecIITR uses regularly or has used at some point.

**Comment by jaybosamiya** [comment]
I believe linking to cheat sheets or quick refs isn't necessary anymore. The first part of this issue is completely, so I am closing this. If anyone believes that the quick refs are needed, please provide a PR for the same.
